spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dasa?currentSchema=mobile&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: dasa
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
